# Generated by Django 3.2 on 2021-04-30 03:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloyalty',
            name='user_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
