# Generated by Django 3.2 on 2021-05-02 00:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='hotel_uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='user_uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
