# Generated by Django 3.2 on 2021-06-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
    ]
