# Generated by Django 3.2 on 2021-05-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210502_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
