# Generated by Django 3.2 on 2021-05-02 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=25)),
                ('short_text', models.CharField(max_length=25)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='фото')),
                ('rooms', models.IntegerField(default=0)),
            ],
        ),
    ]
