# Generated by Django 3.2 on 2021-05-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='location',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
