# Generated by Django 3.2 on 2021-05-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotels_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='short_text',
            field=models.CharField(max_length=255),
        ),
    ]
