# Generated by Django 3.2 on 2021-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotels_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
