# Generated by Django 3.2 on 2021-06-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotels_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='cities',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
