# Generated by Django 3.2 on 2021-06-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotels_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='photo',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
