# Generated by Django 3.2 on 2021-06-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_rename_ava_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
