# Generated by Django 3.2 on 2021-06-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelLikes',
        ),
    ]
