# Generated by Django 3.2 on 2021-06-27 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_delete_hotellikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('hotel_uid', models.UUIDField(default=uuid.uuid4)),
                ('user_uid', models.UUIDField(default=uuid.uuid4)),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_likes', models.IntegerField(default=0)),
                ('comment_dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HotelLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('hotel_likes', models.IntegerField(default=0)),
                ('hotel_dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_uid', models.UUIDField(default=uuid.uuid4)),
                ('user_uid', models.UUIDField(default=uuid.uuid4)),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
            ],
        ),
    ]
