# Generated by Django 3.2 on 2021-06-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20210627_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikes',
            name='avatar',
            field=models.CharField(default='images/avatars/non.jpeg', max_length=30),
        ),
    ]
