# Generated by Django 3.2 on 2021-06-27 22:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_alter_commentlikes_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlikes',
            name='user_uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
