# Generated by Django 3.2 on 2021-06-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_rename_status_userloyalty_status_loyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloyalty',
            name='balance',
            field=models.IntegerField(default=50000),
        ),
    ]
